version: "3.3"

networks:
  springboot-mysql-net:
    external: true

services:

  mysqldb:
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    networks:
      - springboot-mysql-net
    container_name: mysqldb
    ports:
      - "3333:3306"


  achat-1:
    build: .
    restart: on-failure
    networks:
      - springboot-mysql-net
    container_name: achat-1
    ports:
      - "8091:8091"
    depends_on:
      - mysqldb