version: "3.3"

networks:
  network_tarek:
    external: true

services:

  mysqldb:
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    networks:
      - network_tarek
    container_name: mysqldb
    ports:
      - "3333:3306"


  achattarek:
    build: .
    restart: on-failure
    networks:
      - network_tarek
    container_name: achattarek
    ports:
      - "8091:8091"
    depends_on:
      - mysqldb