version: "3.3"
services:

  mysqldb:
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    container_name: mysqldb
    ports:
      - "3306:3306"

  achattarek:
    build: .
    restart: on-failure
    container_name: achattarek
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb