version: "3.3"
services:

  mysqldb:
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    container_name: mysqldb
    ports:
      - "3306:3306"

  achattarek:
    build: .
    restart: on-failure
    container_name: achattarek
    ports:
      - "8091:8091"
    depends_on:
      - mysqldb